# Generated by Django 4.0.6 on 2022-07-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_parking_cost_alter_parking_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='end_date',
            field=models.DateField(blank='-----', null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='end_time',
            field=models.TimeField(blank='-----', null=True),
        ),
    ]
