# Generated by Django 4.0.6 on 2022-07-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_parking_end_date_alter_parking_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='end_date',
            field=models.DateField(blank=True, default='-----', null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
