# Generated by Django 4.0.6 on 2022-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_parking_end_date_alter_parking_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
