# Generated by Django 4.0.5 on 2022-08-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cam_type',
            field=models.CharField(choices=[('Entry Camera', 'Entry Camera'), ('Exit Camera', 'Exit Camera'), ('Security', 'Security')], max_length=100),
        ),
    ]
