# Generated by Django 4.0.5 on 2022-08-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_parking_end_date'),
        ('camera', '0002_alter_camera_cam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.floor'),
        ),
    ]
