# Generated by Django 4.0.5 on 2022-08-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_camera_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='path',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
