# Generated by Django 4.0.6 on 2022-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='reserved_hour_cost',
            field=models.IntegerField(default=1250),
        ),
    ]
