# Generated by Django 4.0.6 on 2022-07-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_reserved_hour_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='hourly_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='reserved_hour_cost',
            field=models.IntegerField(),
        ),
    ]
